---
title: "B4DT vs ERP"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(readr)
library(stringr)
library(tidyr)
```

```{r}
table1 <- read.csv("T0004-10.1080_16506073.2018.1478447.csv")
table1 <- table1 %>%
  mutate(B4DT = NULL)  %>%
  rename(Measurement = X.) %>%
  mutate(ERP = NULL) %>%
  rename(B4DT = X) %>%
  rename(ERP = X.1) 
view(table1)

view(table1)

clean_data <- table1[-c(1,3,5,10), ]
clean_data$B4DT<-gsub("%","",as.character(clean_data$B4DT))
clean_data$ERP<-gsub("%","",as.character(clean_data$ERP))
clean_data$ERP<-gsub("\\*","",as.character(clean_data$ERP))
view(clean_data)

sorted <- levels(clean_data$Measurement) <- c("Declined Treatment", 
  "Dropped Treatment", "Remitted Post-assessment", "Not Remitted", "Relapsed",
  "Recovered (non-remitters)") %>% as_tibble() %>%
  mutate(B4DT = as.numeric(clean_data$B4DT), ERP = as.numeric(clean_data$ERP))
view(sorted)


final_data <- pivot_longer(sorted, cols = 2:3, names_to = "Treatment", values_to = "Proportion") %>%
  rename(Measurement = value) %>%
  group_by(Proportion)
view(final_data)
```

```{r}
final_data %>%
  ggplot(data = final_data, 
         mapping = aes(x = Measurement, y = Proportion, fill = Treatment, group = Treatment)) +
    geom_col( width = 0.8, position = position_dodge2(preserve = "single", reverse = TRUE)) + 
    coord_flip() +
    labs(title = "The Bergen 4 Day Treatment vs Ordinary ERP",
         x = "",
         y = "Proportion out of 100 patients",
         subtitle = "B4DT appears to be more effective, but possibly more temporary",
         caption = "Source: B4DT for OCD: 4 year follow-up of ERP, CBT (2019) Bjarne Hansen et al.")
```

